### ISSUE TITLE
Why my orders doesn't shows up in my transactions field?

### ISSUE THREAD

**Issue by galet0** [decentrex/decentrex.github.io#28]
Hi, I want to sell some tokens, but when I made the order, it doesn't shows up in my transaction. Can you help me please, how to put an order to sell.

**Comment by decentrex** [comment]
The answer is in your question - order is an order, transaction is a transaction. Orders are off chain. Trades are on chain. Once your order is submitted you will see it highlighted in buy or sell section for selected token. When your order will be executed you will see a pending -> confirmed transaction in your trades history. Orders tab is mainly for force canceled orders because order cancellation is ETH transaction too.
